"""Initial schema

Revision ID: 1d9cb324ff2d
Revises:
Create Date: 2026-04-02 14:57:30.095918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d9cb324ff2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription')
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_downloaded', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('local_path', sa.String(length=512), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'manga', ['manga_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.drop_column('source')

    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'manga', ['manga_id'], ['id'])
        batch_op.drop_column('local_path')
        batch_op.drop_column('is_downloaded')

    op.create_table('subscription',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chat_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('manga_id', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
