"""Init

Revision ID: 57b4c4c033c3
Revises:
Create Date: 2026-04-02 16:43:22.812144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b4c4c033c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_downloaded', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('local_path', sa.String(length=512), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'manga', ['manga_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.drop_column('source')

    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'manga', ['manga_id'], ['id'])
        batch_op.drop_column('local_path')
        batch_op.drop_column('is_downloaded')

    # ### end Alembic commands ###
